hunter_config(OpenCV
    VERSION ${HUNTER_OpenCV_VERSION}
    CMAKE_ARGS
    	BUILD_SHARED_LIBS=OFF
    	CMAKE_POSITION_INDEPENDENT_CODE=ON
        OPENCV_WITH_EXTRA_MODULES=YES
)
hunter_config(PNG VERSION ${HUNTER_PNG_VERSION} CMAKE_ARGS BUILD_SHARED_LIBS=OFF CMAKE_POSITION_INDEPENDENT_CODE=ON)
hunter_config(TIFF VERSION ${HUNTER_TIFF_VERSION} CMAKE_ARGS BUILD_SHARED_LIBS=OFF CMAKE_POSITION_INDEPENDENT_CODE=ON)
hunter_config(Jpeg VERSION ${HUNTER_Jpeg_VERSION} CMAKE_ARGS BUILD_SHARED_LIBS=OFF CMAKE_POSITION_INDEPENDENT_CODE=ON)
hunter_config(ZLIB VERSION ${HUNTER_ZLIB_VERSION} CMAKE_ARGS BUILD_SHARED_LIBS=OFF CMAKE_POSITION_INDEPENDENT_CODE=ON)
